# Generated by Django 3.2 on 2021-12-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='meals',
        ),
        migrations.AddField(
            model_name='meals',
            name='components',
            field=models.ManyToManyField(to='menu.Components'),
        ),
        migrations.AlterField(
            model_name='components',
            name='com_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
