# Generated by Django 3.2 on 2021-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211229_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='components',
        ),
        migrations.AddField(
            model_name='components',
            name='meals',
            field=models.ManyToManyField(to='menu.Meals'),
        ),
    ]
