# Generated by Django 3.2 on 2021-12-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20211229_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='com_name',
            new_name='name_com',
        ),
    ]
