# Generated by Django 3.2 on 2022-01-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='components',
        ),
    ]
